# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-09 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='id_pets',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='id_user',
        ),
        migrations.AddField(
            model_name='votes',
            name='date_vote',
            field=models.CharField(default='', editable=False, max_length=15),
        ),
    ]
