# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-09 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('votes', '0002_auto_20191009_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=8)),
                ('votes', models.ManyToManyField(to='votes.Votes')),
            ],
        ),
    ]
