# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-09 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_remove_pets_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='picture',
            field=models.FileField(upload_to=''),
        ),
    ]
